version: 2.1
orbs:
  cypress: cypress-io/cypress@1.7.0
  dockerhub: circleci/docker@0.5.1
executors:
  test:
    docker:
      - image: 'cypress/base:10'
        environment:
          NODE_ENV: test
          SUOTAR_TOKEN: token
      - image: 'circleci/postgres:11-ram'
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
workflows:
  build-test-deploy:
    jobs:
      - run:
        name: Waiting for Postgres to be ready
        command: |
          for i in `seq 1 10`;
          do
            nc -z localhost 5432 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for Postgres && exit 1
      - cypress/run:
          executor: test
          no-workspace: true
          build: npm run test:setup
          start: npm run test:start
          wait-on: 'http-get://localhost:8000'
      - dockerhub/publish:
          requires:
            - cypress/run
          image: $DOCKER_USER/$CIRCLE_PROJECT_REPONAME
          tag: 'staging'
          extra_build_args: '--build-arg BASE_PATH=/suoritustarkistin/'
          filters:
            branches:
              only: trunk
      - dockerhub/publish:
          requires:
            - cypress/run
          image: $DOCKER_USER/$CIRCLE_PROJECT_REPONAME
          tag: 'production'
          extra_build_args: '--build-arg BASE_PATH=/suoritustarkistin/'
          filters:
            branches:
              only: master
